{{- if .Values.secretsManager.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: version-guard-wiz-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.secretsManager.storeName }}
  target:
    name: version-guard-wiz-credentials
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: wiz-client-id
      remoteRef:
        key: {{ .Values.secretsManager.wizSecretKey }}
        property: client_id
    - secretKey: wiz-client-secret
      remoteRef:
        key: {{ .Values.secretsManager.wizSecretKey }}
        property: client_secret
{{- end }}
