{{- if .Values.secretsManager.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secretsManager.storeName }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.secretsManager.serviceAccountName }}
      region: {{ .Values.region }}
      service: SecretsManager
{{- end }}
